# Generated by Django 4.1.1 on 2023-05-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_alter_product_options_remove_sale_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
