product_names = [
    ('Матрас Active A2', 'Матрас Active A2'),
    ('Матрас Active A3', 'Матрас Active A3'),
    ('Матрас Alba Expert', 'Матрас Alba Expert'),
    ('Матрас Alba Favorit', 'Матрас Alba Favorit'),
    ('Матрас Comfort F1', 'Матрас Comfort F1'),
    ('Матрас Comfort F2', 'Матрас Comfort F2'),
    ('Матрас Comfort F3', 'Матрас Comfort F3'),
    ('Матрас Comfort F4', 'Матрас Comfort F4'),
    ('Матрас Comfort F5', 'Матрас Comfort F5'),
    ('Матрас Comfort F6', 'Матрас Comfort F6'),
    ('Матрас Ecolatex L1', 'Матрас Ecolatex L1'),
    ('Матрас Ecolatex L2', 'Матрас Ecolatex L2'),
    ('Матрас Ecolatex L3', 'Матрас Ecolatex L3'),
    ('Матрас Ecolatex L4', 'Матрас Ecolatex L4'),
    ('Матрас Ecolatex L5', 'Матрас Ecolatex L5'),
    ('Матрас Ecolatex L6', 'Матрас Ecolatex L6'),
    ('Матрас Exclusive X1', 'Матрас Exclusive X1'),
    ('Матрас Exclusive X2', 'Матрас Exclusive X2'),
    ('Матрас Exclusive X3', 'Матрас Exclusive X3'),
    ('Матрас Exclusive X4', 'Матрас Exclusive X4'),
    ('Матрас Exclusive X5', 'Матрас Exclusive X5'),
    ('Матрас Exclusive X6', 'Матрас Exclusive X6'),
    ('Матрас Exclusive X7', 'Матрас Exclusive X7'),
    ('Матрас Modern M1', 'Матрас Modern M1'),
    ('Матрас Modern M2', 'Матрас Modern M2'),
    ('Матрас Modern M3', 'Матрас Modern M3'),
    ('Матрас Modern M4', 'Матрас Modern M4'),
    ('Матрас Smart Bingo', 'Матрас Smart Bingo'),
    ('Матрас Smart Drive', 'Матрас Smart Drive'),
    ('Матрас Smart Flash', 'Матрас Smart Flash'),
    ('Матрас Smart Focus', 'Матрас Smart Focus'),
    ('Матрас Smart Joint', 'Матрас Smart Joint'),
    ('Матрас Smart Matrix', 'Матрас Smart Matrix'),
    ('Матрас Smart Profit', 'Матрас Smart Profit'),
    ('Матрас Smart Pulse', 'Матрас Smart Pulse'),
    ('Матрас Smart Sense', 'Матрас Smart Sense'),
    ('Матрас Smart Spark', 'Матрас Smart Spark'),
    ('Матрас Smart Tempo', 'Матрас Smart Tempo'),
    ('Матрас Special Compact2', 'Матрас Special Compact2'),
    ('Матрас Special Hit2', 'Матрас Special Hit2'),
    ('Матрас Special RX', 'Матрас Special RX'),
    ('Матрас Special S3', 'Матрас Special S3'),
    ('Наматрасник Protect Stressfree L4', 'Наматрасник Protect Stressfree L4'),
    ('Наматрасник Protect Stressfree L1', 'Наматрасник Protect Stressfree L1'),
    ('Наматрасник Protect Stressfree S1', 'Наматрасник Protect Stressfree S1'),
    ('Наматрасник Protect Stressfree A1', 'Наматрасник Protect Stressfree A1'),
    ('Наматрасник Protect Bamboo A1', 'Наматрасник Protect Bamboo A1'),
    ('Наматрасник Protect Cotton S1', 'Наматрасник Protect Cotton S1'),
    ('Детский матрас Spring', 'Детский матрас Spring'),
    ('Детский матрас Coco', 'Детский матрас Coco'),
    ('Детский матрас Cocolatex', 'Детский матрас Cocolatex'),
    ('Детский матрас Magic', 'Детский матрас Magic'),
    ('Детский матрас Prince', 'Детский матрас Prince'),
    ('Детский наматрасник FrotteL4', 'Детский наматрасник FrotteL4'),
    ('Детский наматрасник StresfreeL4', 'Детский наматрасник StresfreeL4'),
    ('Основание Suport Super Lux', 'Основание Suport Super Lux'),
    ('Основание Suport Premium', 'Основание Suport Premium'),
    ('Наматрасники Transform Cocos 4cm', 'Наматрасники Transform Cocos 4cm'),
    ('Наматрасники Transform Latex2 4cm', 'Наматрасники Transform Latex2 4cm'),
    ('Наматрасники Transform Latex 5 7cm', 'Наматрасники Transform Latex 5 7cm'),
    ('Наматрасники Transform Mix 6cm', 'Наматрасники Transform Mix 6cm'),
    ('Наматрасники Transform CocosMix 11cm', 'Наматрасники Transform CocosMix 11cm'),
    ('Наматрасники Transform LatexMix 11cm', 'Наматрасники Transform LatexMix 11cm'),
    ('Наматрасники Transform Memory 3 3cm', 'Наматрасники Transform Memory 3 3cm'),
    ('Наматрасники Transform Memory 6 6cm', 'Наматрасники Transform Memory 6 6cm'),
    ('Наматрасники Transform Flexy 3 3cm', 'Наматрасники Transform Flexy 3 3cm'),
    ('Наматрасники Transform Flexy 6 6cm', 'Наматрасники Transform Flexy 6 6cm'),
    ('Кровать Victoria', 'Кровать Victoria'),
    ('Кровать Belona', 'Кровать Belona'),
    ('Кровать Julia', 'Кровать Julia'),
    ('Кровать Madlen', 'Кровать Madlen'),
    ('Кровать Deliya', 'Кровать Deliya'),
    ('Кровать Nox', 'Кровать Nox'),
    ('Кровать Dolores', 'Кровать Dolores'),
    ('Кровать Elizabeth', 'Кровать Elizabeth'),
    ('Кровать Florence', 'Кровать Florence'),
    ('Кровать Milana', 'Кровать Milana'),
    ('Кровать Elen', 'Кровать Elen'),
    ('Кровать Naomi', 'Кровать Naomi'),
    ('Кровать Bianca', 'Кровать Bianca'),
    ('Кровать Leto f/m', 'Кровать Leto f/m'),
    ('Кровать Leto c/m', 'Кровать Leto c/m'),
    ('Кровать Lera f/m', 'Кровать Lera f/m'),
    ('Кровать Lera c/m', 'Кровать Lera c/m'),
    ('Кровать Mary', 'Кровать Mary'),
    ('Кровать Alise', 'Кровать Alise'),
    ('Кровать Chris', 'Кровать Chris'),
    ('Подушка Sleep Constructor', 'Подушка Sleep Constructor'),
    ('Подушка №8 60x41x12', 'Подушка №8 60x41x12'),
    ('Подушка №9 60x40x12', 'Подушка №9 60x40x12'),
    ('Подушка №11 60x41x12', 'Подушка №11 60x41x12'),
    ('Подушка №14 60x40x12', 'Подушка №14 60x40x12'),
    ('Подушка №16 66x42x12', 'Подушка №16 66x42x12'),
    ('Подушка №17 62x42x12', 'Подушка №17 62x42x12'),
    ('Подушка LatexRoyal', 'Подушка LatexRoyal'),
    ('Подушка Memoryextra', 'Подушка Memoryextra'),
    ('Подушка №19 70x50x12', 'Подушка №19 70x50x12'),
    ('Подушка №20 60x40x12', 'Подушка №20 60x40x12'),
    ('Подушка №21 60x40x12', 'Подушка №21 60x40x12'),
    ('Подушка Babyboom 200', 'Подушка Babyboom 200'),
    ('Подушка Babyboom 250', 'Подушка Babyboom 250'),
    ('Подушка Bimbo', 'Подушка Bimbo'),
    ('Подушка Junior 52x30x10', 'Подушка Junior 52x30x10'),
    ('Подушка Nanomem', 'Подушка Nanomem'),
    ('Подушка Beauty', 'Подушка Beauty'),
    ('Тумбочка Davout – 50х42х41', 'Тумбочка Davout – 50х42х41'),
    ('Тумбочка Marbot – 50х42х46', 'Тумбочка Marbot – 50х42х46'),
    ('Тумбочка Junot – 50х42х41', 'Тумбочка Junot – 50х42х41'),
    ('Пуф Vicont – 40х40х43', 'Пуф Vicont – 40х40х43'),
    ('Тумбочка KING – 50х45х58', 'Тумбочка KING – 50х45х58'),
    ('Тумбочка Biatrice – 60х45х56', 'Тумбочка Biatrice – 60х45х56'),
    ('Пуф FILIP – 34х34х37', 'Пуф FILIP – 34х34х37'),
    ('Пуф Liudovic I – 43х45х45', 'Пуф Liudovic I – 43х45х45'),
    ('Пуф Liudovic II – 43х43х46', 'Пуф Liudovic II – 43х43х46'),
    ('Одеяло Бамбук 110х140 BambooW', 'Одеяло Бамбук 110х140 BambooW'),
    ('Одеяло Бамбук 140х205 BambooA', 'Одеяло Бамбук 140х205 BambooA'),
    ('Одеяло Бамбук 172х205 BambooA', 'Одеяло Бамбук 172х205 BambooA'),
    ('Одеяло Бамбук 200х220 BambooA', 'Одеяло Бамбук 200х220 BambooA'),
    ('Одеяло Бамбук 140х205 BambooW', 'Одеяло Бамбук 140х205 BambooW'),
    ('Одеяло Бамбук 172х205 BambooW', 'Одеяло Бамбук 172х205 BambooW'),
    ('Одеяло Бамбук 200х220 BambooW', 'Одеяло Бамбук 200х220 BambooW'),
    ('Одеяло Овечья шерсть 140х205 Sheep A', 'Одеяло Овечья шерсть 140х205 Sheep A'),
    ('Одеяло Овечья шерсть 172х205 Sheep A', 'Одеяло Овечья шерсть 172х205 Sheep A'),
    ('Одеяло Овечья шерсть 200х220 Sheep A', 'Одеяло Овечья шерсть 200х220 Sheep A'),
    ('Одеяло Овечья шерсть 140х205 Sheep W', 'Одеяло Овечья шерсть 140х205 Sheep W'),
    ('Одеяло Овечья шерсть 172х205 Sheep W', 'Одеяло Овечья шерсть 172х205 Sheep W'),
    ('Одеяло Овечья шерсть 200х220 Sheep W', 'Одеяло Овечья шерсть 200х220 Sheep W'),
    ('Одеяло Sum Win W 140х205 SunWinW', 'Одеяло Sum Win W 140х205 SunWinW'),
    ('Одеяло Sum Win W 172х205 SunWinW', 'Одеяло Sum Win W 172х205 SunWinW'),
    ('Одеяло Sum Win W 200х220 SunWinW', 'Одеяло Sum Win W 200х220 SunWinW'),
    ('Вариант 131Victoria', 'Вариант 131Victoria'),
    ('Belona', 'Belona'),
    ('Julia', 'Julia'),
    ('Julia 2', 'Julia 2'),
    ('Elen', 'Elen'),
    ('Milana', 'Milana'),
    ('Milana 2', 'Milana 2'),
    ('Milana 3', 'Milana 3'),
    ('Milana 4', 'Milana 4'),
    ('Carmen', 'Carmen'),
    ('Terra', 'Terra'),
    ('Michelle', 'Michelle'),
    ('Dolores', 'Dolores'),
    ('Madlen', 'Madlen'),
    ('Delija', 'Delija'),
    ('Elizabeth', 'Elizabeth'),
    ('Floremce', 'Floremce'),
    ('Nox', 'Nox'),
    ('Naomi', 'Naomi'),
    ('Marshal', 'Marshal'),
    ('Bianca', 'Bianca'),
    ('Letto', 'Letto'),
    ('Lera', 'Lera'),
    ('Chris', 'Chris'),
    ('Alise', 'Alise'),
    ('Mari', 'Mari')
]

sizes = [
    ('90x200', '90x200'),
    ('90x190', '90x190'),
    ('80x200', '80x200'),
    ('70x140', '70x140'),
    ('65x125', '65x125'),
    ('60x120', '60x120'),
    ('200x200', '200x200'),
    ('190x200', '190x200'),
    ('180x200', '180x200'),
    ('170x200', '170x200'),
    ('160x200', '160x200'),
    ('160x190', '160x190'),
    ('150x200', '150x200'),
    ('140x200', '140x200'),
    ('140x190', '140x190'),
    ('130x200', '130x200'),
    ('120x200', '120x200'),
    ('110x200', '110x200'),
    ('100x200', '100x200'),
    ('Не стандартный размер', 'Не стандартный размер')
]

shops = [
    ('Джамбо', 'Джамбо'),
    ('Рышкановка', 'Рышкановка'),
    ('Крянгэ', 'Крянгэ'),
    ('Зелинского', 'Зелинского'),
    ('Офис', 'Офис'),
    ('Чеканы', 'Чеканы')
]

salesmen = [
    ('_', '_')
]